### PR TITLE
Add auto-registry option for lazy developers.

### PR DESCRIPTION
**Pull request by portlek**
Added FastBoardRegistry.
Updated README for the usage of the new auto-registry system.
image

### CODE REVIEW

**Comment by iiAhmedYT** [comment]
well if your comments are like this I'd rather NOT comment.
image

**Comment by hausemaster3734** [comment]
> well if your comments are like this I'd rather NOT comment. image

I don't understand who is still using doc blocks in java...

**Comment by portlek** [comment]
you guys can change javadocs later, it's just for placeholder.

**Comment by MrMicky-FR** [comment]
Hi, thanks for your pull request, and I apologize for the long delay, however after some consideration I don't think it's fit the project goal, which is to be a "basic" (in features) scoreboard class and not a full-flagged scoreboard framework

**Pull request closed without merging**
