### PR TITLE
Resolving StringIndexOutOfBoundsException

### PR DESCRIPTION
**Pull request by fleivinho**
Caused by: java.lang.StringIndexOutOfBoundsException: Range [0, 16) out of bounds for length 15

### CODE REVIEW

**Comment by MrMicky-FR** [comment]
How this issue can be reproduced? Also this is not good as you could split on a color char which would be invalid for the client

**Comment by MrMicky-FR** [comment]
https://github.com/MrMicky-FR/FastBoard/blob/402661cfb8d531596324c48c2506e478269c62b0/src/main/java/fr/mrmicky/fastboard/FastBoard.java#L103-L109

I'm closing this for now as the error seems impossible: if `line.length()` is lower or equal than `maxLength`, then the `else if`(lines 103-104 above) will be executed, and not the `split` in the `else`.

And if `line.length()` is strictly greater than `maxLength`, then there is no reason splitting on an index strictly lower than the line length would cause an `StringIndexOutOfBoundsException`.

But feel free to respond here in case I missed something, it's always possible to re-open a closed PR, thanks!

**Comment by fleivinho** [comment]
Sorry for the lateness. Well, this error started happening when I updated the code to the latest version of FastBoard. I only tested it on version 1.8.8. That "fix" I applied was enough to avoid this error.

I'm not sure if it's just an isolated case, but both me and my users experienced the same issue.

https://www.youtube.com/watch?v=L_uLOwZVqfk

**Comment by MrMicky-FR** [comment]
Neither the line numbers nor the class name in the error match the original class, could you test again by using the original FastBoard class without **any** modification (ideally you should use Maven or Gradle for dependency management), so that we can try to understand this problem? Thanks a lot!

**Pull request closed without merging**
